#!/bin/bash

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "❌ This script requires root privileges. Please run with sudo."
    exit 1
fi

# Detect distribution
if [ -f /etc/os-release ]; then
    . /etc/os-release
    DISTRO=$NAME
    VERSION=$VERSION_ID
    ID=$ID
else
    echo "❌ Could not detect distribution"
    exit 1
fi

# Function to install required packages based on distribution
install_required_packages() {
    echo "📦 Checking and installing required packages..."

    MISSING=""
    for cmd in dmidecode smartctl inxi lshw; do
        if ! command -v $cmd &>/dev/null; then
            MISSING+="$cmd "
        fi
    done

    if [ -z "$MISSING" ]; then
        echo "✅ All required packages are already installed."
        return
    fi

    echo "📦 Missing tools: $MISSING"
    read -p "Do you want to install the missing packages? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Installation cancelled. Exiting..."
        exit 1
    fi

    case $ID in
        "ubuntu"|"debian")
            apt-get update
            apt-get install -y $MISSING
            ;;
        "centos"|"rhel"|"fedora"|"rocky"|"almalinux"|"ol")
            if command -v dnf &> /dev/null; then
                dnf install -y $MISSING
            else
                yum install -y $MISSING
            fi
            ;;
        "arch"|"manjaro")
            pacman -Sy --noconfirm $MISSING
            ;;
        *)
            echo "⚠️ Unsupported distribution: $DISTRO ($ID)"
            echo "Please install the following packages manually: $MISSING"
            read -p "Press Enter to continue or Ctrl+C to exit..."
            ;;
    esac
}

# Install required packages
install_required_packages

# Set output file
OUTPUT="/tmp/hardware_report_$(hostname)_$(date +%Y-%m-%d_%H-%M-%S).txt"

echo "Gathering system hardware info... Output will be saved to: $OUTPUT"
echo "Hardware Report - $(hostname) - $(date)" > "$OUTPUT"
echo "==================================================" >> "$OUTPUT"

# CPU Info
echo -e "\n🧠 CPU Info" >> "$OUTPUT"
echo "------------------------" >> "$OUTPUT"
lscpu >> "$OUTPUT"
echo -e "\nCPU Model: $(grep -m1 'model name' /proc/cpuinfo | cut -d':' -f2 | xargs)" >> "$OUTPUT"
echo "CPU Count: $(grep -c ^processor /proc/cpuinfo)" >> "$OUTPUT"

# RAM Info
echo -e "\n🧠 RAM Info (Grouped by Device)" >> "$OUTPUT"
echo "------------------------" >> "$OUTPUT"
dmidecode --type memory | awk '
  /^Memory Device$/ {print "\n----------------------------"}
  /^Size:|^Speed:|^Manufacturer:|^Part Number:/ {print $0}
' >> "$OUTPUT"

# Disk Info
echo -e "\n💽 Disk Info" >> "$OUTPUT"
echo "------------------------" >> "$OUTPUT"
lsblk -o NAME,SIZE,TYPE,MODEL,SERIAL >> "$OUTPUT"

for dev in $(lsblk -dn -o NAME,TYPE | awk '$2=="disk"{print $1}'); do
    echo -e "\nSMART Info for /dev/$dev" >> "$OUTPUT"
    smartctl --info /dev/$dev >> "$OUTPUT" 2>/dev/null
done

# GPU Info
echo -e "\n🎮 GPU Info" >> "$OUTPUT"
echo "------------------------" >> "$OUTPUT"
inxi -Gxx >> "$OUTPUT"
lspci | grep -i vga >> "$OUTPUT"
echo -e "\nFull GPU Details:" >> "$OUTPUT"
lshw -C display >> "$OUTPUT" 2>/dev/null


# Present options to the user
echo -e "\nWhat would you like to do next?"
echo "1) View report contents"
echo "2) Open with less"
echo "3) Print report path only"
echo "4) Do nothing"
read -p "Enter your choice [1-4]: " choice

case $choice in
    1)
        echo -e "\n📄 Report contents:"
        echo "----------------------------------------"
        cat "$OUTPUT"
        echo "----------------------------------------"
        ;;
    2)
        less "$OUTPUT"
        ;;
    3)
        echo "$REPORT_PATH"
        ;;
    *)
        echo "👍 Done. You can open the report anytime at:"
        echo "$REPORT_PATH"
        ;;
esac

# Footer
echo -e "\n🔗 Generated by PCSP Hardware Info Script - https://github.com/PCSP-DevSolutions/.github" >> "$OUTPUT"

# Always show the absolute path
echo -e "\n📁 Full path to report: $(realpath "$OUTPUT")"
